import { mdiCarMultiple, mdiCarWireless, mdiCarWrench, mdiCart, mdiLogout, mdiAccountGroup, mdiCog, mdiMailboxOpenUpOutline, mdiStoreClock, mdiStore, mdiBellOutline, mdiAccount, mdiViewDashboardVariant, mdiWeb, mdiCarSearchOutline, mdiAlert, mdiArrowUpBold, mdiArrowDownBold, mdiCalendar, mdiChartLine, mdiContentSave, mdiAccountDetails, mdiInformationOutline, mdiAlertCircle, mdiEye, mdiEyeOff} from "@mdi/js";

export const icons = {
CarMultiple: mdiCarMultiple,
CarWireless: mdiCarWireless,
CarWrench: mdiCarWrench,
Cart: mdiCart,
Logout: mdiLogout,
Accountgroup: mdiAccountGroup,
Cog: mdiCog,
MailboxOpenUpOutline: mdiMailboxOpenUpOutline,
StoreClock: mdiStoreClock,
Store: mdiStore,
BellOutline: mdiBellOutline,
Account: mdiAccount,
ViewDashboardVariant: mdiViewDashboardVariant,
Web: mdiWeb,
CarSearchOutline: mdiCarSearchOutline,
Alert: mdiAlert,
ArrowUpBold: mdiArrowUpBold,
ArrowDownBold: mdiArrowDownBold,
Calender: mdiCalendar,
ChartLine: mdiChartLine,
ContentSave: mdiContentSave,
AccountDetails: mdiAccountDetails,
iInformationOutline: mdiInformationOutline,
AlertCircle: mdiAlertCircle,
Eye: mdiEye,
EyeOff: mdiEyeOff,
};