import { mdiCarMultiple, mdiCarWireless, mdiCarWrench, mdiCart, mdiLogout, mdiAccountGroup, mdiCog, mdiMailboxOpenUpOutline, mdiStoreClock, mdiStore, mdiBellOutline, mdiAccount, mdiViewDashboardVariant, mdiWeb, mdiCarSearchOutline, mdiAlert, mdiArrowUpBold, mdiArrowDownBold, mdiCalendar, mdiChartLine, mdiContentSave, mdiAccountDetails, mdiInformationOutline, mdiAlertCircle, mdiEye, mdiEyeOff, mdiCreditCardWireless, mdiChevronRight, mdiChevronDown, mdiChevronUp, mdiCircleSmall} from "@mdi/js";

export const icons = {
CarMultiple: mdiCarMultiple,
CarWrench: mdiCarWrench,
Cart: mdiCart,
Logout: mdiLogout,
AccountGroup: mdiAccountGroup,
Cog: mdiCog,
MailboxOpenUpOutline: mdiMailboxOpenUpOutline,
StoreClock: mdiStoreClock,
Store: mdiStore,
BellOutline: mdiBellOutline,
Account: mdiAccount,
ViewDashboardVariant: mdiViewDashboardVariant,
Web: mdiWeb,
CarSearchOutline: mdiCarSearchOutline,
Alert: mdiAlert,
ArrowUpBold: mdiArrowUpBold,
ArrowDownBold: mdiArrowDownBold,
Calendar: mdiCalendar,
ChartLine: mdiChartLine,
CarWireless: mdiCreditCardWireless,
ContentSave: mdiContentSave,
AccountDetails: mdiAccountDetails,
InformationOutline: mdiInformationOutline,
AlertCircle: mdiAlertCircle,
Eye: mdiEye,
EyeOff: mdiEyeOff,
CarWireless: mdiCarWireless,
ChevronRight: mdiChevronRight,
ChevronDoubleDown: mdiChevronDown,
ChevronDoubleUp: mdiChevronUp,
CircleSmall: mdiCircleSmall,
};